name: cdu_helper
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.16
  cookie_jar: ^1.0.0
  fluttertoast: 3.1.3
  provide: 1.0.2
  oktoast: ^2.1.7
  shared_preferences: ^0.5.1
  fluro: 1.4.0
  flutter_easyrefresh: 1.2.7
  url_launcher: 5.0.2
  flutter_swiper : ^1.1.4
  flutter_screenutil: ^0.5.3
  sqflite: ^1.1.7+1
  gbk2utf8: ^1.0.0
  html: ^0.14.0+3
  flutter_html: ^0.11.0
  data_plugin: ^0.0.12
  pin_input_text_field: ^2.0.0
  image_picker: 0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: HuaWenXinWei
      fonts:
        - asset: fonts/HuaWenXinWei-1.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/loginAndRegister/loginFooter.png
    - lib/images/loginAndRegister/title.png
    - lib/images/loginAndRegister/titleLine.png
    - lib\images\loginAndRegister\boy.png
    - lib\images\loginAndRegister\girl.png
    - lib\images\splash\splash_image.png
    - lib\images\loginAndRegister\boySeletd.png
    - lib\images\loginAndRegister\girlSeleted.png
    - lib\images\loginAndRegister\border.png
    - lib\images\loginAndRegister\bianji.png
    - lib\images\loginAndRegister\moren.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
